apiVersion : apps/v1
kind: Deployment

metadata:                                     ### Описание деплоймента
  name: mygifservice-deployment               # Название деплоймента
  labels:                                     # Лейбл деплоймента
    app: mygifservice-app
    env: prod
    owner: OlegFilatov

spec:                                         ### Спецификация
  replicas: 3                                 # !Количество реплик пода

  selector:
    matchLabels:                              # С какими лейблами подов будет работать деплоймент
      app: mygifservice-app
      project: mygifservice-project

  template:                                   ### Описание подов
    metadata:                                 ## Описание пода № 1
      labels:                                 # Лейблы подов Должны совпадать с selector
        app: mygifservice-app
        project: mygifservice-project
    spec:
      containers:                             # Какие контейнеры будут запускаться в подах
      - name: mygifservice-container
        image: fillswim/mygifservice:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
