# Nginx values for my template Helm Chart
container:
  image: nginx:latest                             # {{ .Values.container.image }}

containerPort: 80                                 # {{ .Values.containerPort }}

servicePort: 81                                   # {{ .Values.servicePort }}

cpuUtilization: 50                                # {{ .Values.cpuUtilization }}

memoryUtilization: 80                             # {{ .Values.memoryUtilization }}

host: nginx.fillswim.com                          # {{ .Values.host }}