kind: PersistentVolumeClaim

# kubectl apply -f Courses/Kryukov/Volumes/06-PV-PVC/02-Dynamic-PV/01-PVC.yaml
# kubectl delete -f Courses/Kryukov/Volumes/06-PV-PVC/02-Dynamic-PV/01-PVC.yaml

apiVersion: v1
metadata:
  name: claim-nfs-pvc
  namespace: volumes-sample

spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi