apiVersion: v1

# kubectl apply -f Volumes/PersistentVolume/01-static-pv/local/01-create-pv.yaml
# kubectl delete -f Volumes/PersistentVolume/01-static-pv/local/01-create-pv.yaml

kind: PersistentVolume                  # Кластерная сущность, namespace не указывается
metadata:
  name: test-local                      # Название PV (может использоваться в манифесте создания PVC)
spec:
  accessModes:
  - ReadWriteOnce                       # том может быть смонтирован на чтение и запись к одному поду
  capacity:
    storage: 1Gi
  local:
    path: /opt/local-pv                 # Папка на node4 (нужно ее создать)
  nodeAffinity:                         # Т.к. выбран "path: /opt/local-pv", необходимо выбрать ноду, на которой будет PV
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node4                       # наименование ноды 
  persistentVolumeReclaimPolicy: Retain # pv удален не будет