apiVersion: v1

# kubectl apply -f Volumes/PersistentVolume/01-static-pv/local/02-create-pvc.yaml
# kubectl delete -f Volumes/PersistentVolume/01-static-pv/local/02-create-pvc.yaml

kind: PersistentVolumeClaim
metadata:
  name: claim-local-pvc           # Название PVC (будет использоваться в манифесте создания Пода)
  namespace: volumes-sample
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi                # Желаемый объем PV
  volumeName: test-local          # (Опционально) Название PV, которое хочется занять