apiVersion: apps/v1

# kubectl apply -f Volumes/PersistentVolume/01-static-pv/local/04-create-deployment.yaml
# kubectl delete -f Volumes/PersistentVolume/01-static-pv/local/04-create-deployment.yaml

kind: Deployment
metadata:
  name: openresty-local
  namespace: volumes-sample
  labels:
    app: openresty
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: openresty
  template:
    metadata:
      labels:
        app: openresty
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: kubernetes.io/hostname
#                operator: In
#                values:
#                - node4                       # наименование ноды
      containers:
      - name: openresty
        image: openresty/openresty:centos-rpm
        imagePullPolicy: IfNotPresent
        env:
        - name: NGINX_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: "0.2"
            memory: "300Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - mountPath: /mnt/local
            name: claim-volume
      volumes:
        - name: claim-volume
          persistentVolumeClaim:
            claimName: claim-local-pvc