apiVersion: v1

# kubectl apply -f Courses/Kryukov/Volumes/06-PV-PVC/01-Static-PV/local/02-PVC.yaml
# kubectl delete -f Courses/Kryukov/Volumes/06-PV-PVC/01-Static-PV/local/02-PVC.yaml

kind: PersistentVolumeClaim
metadata:
  name: claim-local-pvc           # Название PVC (будет использоваться в манифесте создания Пода)
  namespace: volumes-sample
spec:
  storageClassName: ""            # Чтобы не выбрать SC, который назначен по умолчанию
  accessModes:
  - ReadWriteOnce                 # # том может быть смонтирован на чтение и запись к одному поду
  resources:
    requests:
      storage: 1Gi                # Желаемый объем PV
  volumeName: test-local          # (Опционально) Название PV, которое хочется занять