apiVersion : apps/v1

# kubectl apply -f Courses/Kryukov/Volumes/06-PV-PVC/01-Static-PV/local/04-Deployment.yaml
# kubectl delete -f Courses/Kryukov/Volumes/06-PV-PVC/01-Static-PV/local/04-Deployment.yaml

kind: Deployment
metadata:                                     ### Описание деплоймента
  name: mygifservice-deployment               # Название деплоймента
  namespace: volumes-sample
  labels:                                     # Лейбл деплоймента
    app: mygifservice-app

spec:                                         ### Спецификация
  replicas: 1                                 # Т.к. в PV и PVC AccessModes: ReadWriteOnce (Volume доступен только на одном поде) 

  selector:
    matchLabels:                              # С какими лейблами подов будет работать деплоймент
      app: mygifservice-app
      project: mygifservice-project

  template:                                   ### Описание подов
    metadata:                                 ## Описание пода № 1
      labels:                                 # Лейблы подов Должны совпадать с selector
        app: mygifservice-app
        project: mygifservice-project
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: kubernetes.io/hostname
#                operator: In
#                values:
#                - node4                      # наименование ноды
      containers:                             # Какие контейнеры будут запускаться в подах
      - name: mygifservice-container
        image: fillswim/mygifservice:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /mnt/local             # куда монтируется PVC внутри контейнера
            name: claim-volume
      volumes:
        - name: claim-volume
          persistentVolumeClaim:
            claimName: claim-local-pvc        # наименование монтируемого PVC
