apiVersion: v1

# kubectl apply -f DB/MySQL/01-Secret.yaml
# kubectl delete -f DB/MySQL/01-Secret.yaml

kind: Secret
metadata:
  name: mysql-password
  namespace: statefulset-example
type: opaque
stringData:
  MYSQL_ROOT_PASSWORD: password