apiVersion : apps/v1
kind: Deployment
metadata:                                               ### Описание деплоймента
  name: {{ .Release.name }}-deployment                         # Название деплоймента (будет использоваться в автоселлере)
  labels:                                               # Лейбл деплоймента
    app: {{ .Release.name }}-app
    env: prod
    owner: OlegFilatov
spec:                                                   ### Спецификация
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:                                        # С какими лейблами подов будет работать деплоймент
      app: mygifservice-pod
      project: mygifservice-project

  template:                                             ### Описание подов
    metadata:                                           ## Описание пода № 1
      labels:                                           # Лейблы подов Должны совпадать с selector
        app: mygifservice-pod
        project: mygifservice-project
    spec:
      containers:                                       # Какие контейнеры будут запускаться в подах
      - name: mygifservice-container
        image: {{ .Values.container.image }}             # Можно менять версии (Является япеременной в Helm Chart)
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080