apiVersion: v1                            ### Описание Сервиса
kind: Service

metadata:                                 # Имя сервиса
  name: mygifservice-service
  labels:                                 # Лейблы сервиса
    env: prod
    owner: OlegFilatov

spec:
  type: LoadBalancer                      # Тип сервиса

  selector:
    app: mygifservice-pod                 #! На поды с какими лейблами будет работать сервис, распространять трафик
    project: mygifservice-project

  ports:
  - port: 8080                            # Какой на Load Balancer будет открыть порт (внешний)
    targetPort: 8080                      #!! Порт на поде