apiVersion : apps/v1
kind: Deployment
metadata:                                               ### Описание деплоймента
  name: mygif-deployment-autoscaling                    # Название деплоймента (будет использоваться в автоселлере)
  labels:                                               # Лейбл деплоймента
    app: mygif-app
    env: prod
    owner: OlegFilatov
spec:                                                   ### Спецификация

  selector:
    matchLabels:                                        # С какими лейблами подов будет работать деплоймент
      app: mygif-app
      project: mygif-project-autoscaling

  template:                                             ### Описание подов
    metadata:                                           ## Описание пода № 1
      labels:                                           # Лейблы подов Должны совпадать с selector
        app: mygif-app
        project: mygif-project-autoscaling
    spec:
      containers:                                       # Какие контейнеры будут запускаться в подах
      - name: mygif-container
        image: fillswim/mygifservice:latest             # Можно менять версии (Является япеременной в Helm Chart)
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: autoscaling/v2                              ### Описание autoscaling
kind: HorizontalPodAutoscaler

metadata:
  name: mygig-autoscaling                               # Название autoscaling

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment                                    # Что будет аутоскелить - Deployment
    name: mygif-deployment-autoscaling                  # Название деплоймента, который будет аутоскелиться

  minReplicas: 2                                        # Минимальное количество подов
  maxReplicas: 6                                        # Максимальное количество подов

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

