apiVersion : apps/v1
kind: Deployment
metadata:                                               ### Описание деплоймента
  name: mygifservice-deployment                         # Название деплоймента (будет использоваться в автоселлере)
  labels:                                               # Лейбл деплоймента
    app: mygifservice-app
    env: prod
    owner: OlegFilatov
spec:                                                   ### Спецификация

  selector:
    matchLabels:                                        # С какими лейблами подов будет работать деплоймент
      app: mygifservice-pod
      project: mygifservice-project

  template:                                             ### Описание подов
    metadata:                                           ## Описание пода № 1
      labels:                                           # Лейблы подов Должны совпадать с selector
        app: mygifservice-pod
        project: mygifservice-project
    spec:
      containers:                                       # Какие контейнеры будут запускаться в подах
      - name: mygifservice-container
        image: fillswim/mygifservice:latest             # Можно менять версии (Является япеременной в Helm Chart)
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: autoscaling/v2                              ### Описание autoscaling
kind: HorizontalPodAutoscaler

metadata:
  name: mygifservice-autoscaling                        # Название autoscaling

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment                                    # Что будет аутоскелить - Deployment
    name: mygifservice-deployment                       # Название деплоймента, который будет аутоскелиться

  minReplicas: 2                                        # Минимальное количество подов
  maxReplicas: 6                                        # Максимальное количество подов

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50                          # Если средняя нагрузка на поды будет выше 50%, то autoscaling добавит подов, если ниже, по убавит их количество

  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80                          # Если средняя нагрузка на поды будет выше 80%, то autoscaling добавит подов, если ниже, по убавит их количество
