apiVersion: v1

# kubectl apply -f Courses/BAKAVETS/38-Affinity/02-Pod-NodeSelector.yaml
# kubectl delete -f Courses/BAKAVETS/38-Affinity/02-Pod-NodeSelector.yaml

kind: Pod
metadata:
  name: nginx
  namespace: affinity-example

  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
    imagePullPolicy: IfNotPresent

  nodeSelector:
    disktype: ssd
