apiVersion: v1

# kubectl apply -f Courses/BAKAVETS/38-Affinity/03-Pod-NodeName.yaml
# kubectl delete -f Courses/BAKAVETS/38-Affinity/03-Pod-NodeName.yaml

kind: Pod
metadata:
  name: nginx
  namespace: affinity-example

spec:
  nodeName: node6 # schedule pod to specific node
  containers:
  - name: nginx
    image: nginx
    resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
    imagePullPolicy: IfNotPresent