apiVersion: v1

# kubectl apply -f Courses/Kryukov/Volumes/06-PV-PVC/01-Static-PV/nfs/02-PVC.yaml
# kubectl delete -f Courses/Kryukov/Volumes/06-PV-PVC/01-Static-PV/nfs/02-PVC.yaml

kind: PersistentVolumeClaim
metadata:
  name: claim-nfs-pvc           # Название PVC (будет использоваться в манифесте создания Пода)
  namespace: volumes-sample
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi                # Желаемый объем PV
  #volumeName: test-nfs           # (Опционально) Название PV, которое хочется занять