---
apiVersion: v1

# kubectl apply -f Courses/ThatDevOpsGuy/StatefulSets/01-NameSpace.yaml
# kubectl delete -f Courses/ThatDevOpsGuy/StatefulSets/01-NameSpace.yaml

kind: Namespace
metadata:
  name: statefulset-example
  labels:
    app: statefulset-example